EMERGENCY_SERVICES = [
    {
        "id": "hosp-1",
        "type": "hospital",
        "name": "Apollo Speciality Hospital OMR",
        "phone": "+91 44 4203 7777",
        "lat": 12.9436,
        "lng": 80.2362,
        "available": True,
        "tags": ["trauma", "emergency", "24x7"],
    },
    {
        "id": "hosp-2",
        "type": "hospital",
        "name": "Adyar Trauma Care Unit",
        "phone": "+91 44 2441 2345",
        "lat": 13.0068,
        "lng": 80.2570,
        "available": True,
        "tags": ["trauma", "icu"],
    },
    {
        "id": "amb-1",
        "type": "ambulance",
        "name": "108 Emergency Ambulance",
        "phone": "108",
        "lat": 13.0105,
        "lng": 80.2209,
        "available": True,
        "tags": ["government", "24x7"],
    },
    {
        "id": "amb-2",
        "type": "ambulance",
        "name": "Private Ambulance Partner",
        "phone": "+91 98840 00000",
        "lat": 12.9874,
        "lng": 80.2181,
        "available": False,
        "tags": ["fallback"],
    },
    {
        "id": "police-1",
        "type": "police",
        "name": "Adyar Traffic Police Station",
        "phone": "100",
        "lat": 13.0014,
        "lng": 80.2565,
        "available": True,
        "tags": ["traffic", "crash-report"],
    },
]

